"""Domain models for the SelfRep self-representation dossier builder.

These models are deliberately plain dataclasses so the pipeline remains
deterministic, serializable, and independent of any LLM backend.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass(frozen=True)
class Actor:
    """A party or person involved in the SelfRep dossier."""

    actor_id: str
    display_name: str
    party_role: str  # e.g. claimant, employer, insurer, union, medical
    email_addresses: tuple[str, ...] = ()
    domains: tuple[str, ...] = ()
    aliases: tuple[str, ...] = ()
    stake: str = ""
    authority_level: str = "unknown"  # primary, secondary, hearsay, unknown


@dataclass(frozen=True)
class Artifact:
    """A single piece of evidence extracted by ANCHORUM."""

    artifact_id: str
    source_path: str
    filename: str
    container_type: str  # email, pdf, ooxml, jpeg, png, mp4, etc.
    modality: str  # email, document, image, video, audio, text, unknown
    timestamp: datetime | None
    content_text: str
    metadata: dict[str, Any] = field(default_factory=dict)
    anomalies: tuple[str, ...] = ()
    extraction_errors: tuple[str, ...] = ()


@dataclass(frozen=True)
class Claim:
    """A proposition extracted from one or more artifacts."""

    claim_id: str
    text: str
    source_artifact_ids: tuple[str, ...]
    actor_id: str
    timestamp: datetime | None
    modality: str
    claim_type: str = "assertion"  # assertion, request, refusal, admission, obligation
    party_role: str = ""
    confidence: float = 1.0
    extracted_by: str = "deterministic"  # deterministic, llm_enrichment
    supporting_evidence_ids: tuple[str, ...] = ()


@dataclass(frozen=True)
class ThreadMessage:
    """One message inside an email thread."""

    artifact_id: str
    actor_id: str
    timestamp: datetime | None
    subject: str
    in_reply_to: tuple[str, ...] = ()
    references: tuple[str, ...] = ()
    body_excerpt: str = ""


@dataclass(frozen=True)
class Thread:
    """A reconstructed email or message thread."""

    thread_id: str
    subject: str
    messages: tuple[ThreadMessage, ...]
    participants: tuple[str, ...]
    initiator: str = ""


@dataclass(frozen=True)
class Contradiction:
    """A conflict between two claims."""

    claim_a_id: str
    claim_b_id: str
    reason: str
    normalized_subject: str
    confidence: float


@dataclass(frozen=True)
class Corroboration:
    """Agreement between two independent claims."""

    claim_a_id: str
    claim_b_id: str
    reason: str
    normalized_subject: str
    confidence: float


@dataclass(frozen=True)
class EvidenceGap:
    """A missing piece of evidence that weakens a claim or issue."""

    gap_id: str
    description: str
    related_actor_ids: tuple[str, ...]
    related_claim_ids: tuple[str, ...]
    severity: str  # high, medium, low
    gap_type: str  # missing_document, missing_response, missing_corroboration, anomaly, silent_period


@dataclass(frozen=True)
class Dossier:
    """The complete self-representation dossier."""

    case_id: str
    generated_at: datetime
    actors: tuple[Actor, ...]
    artifacts: tuple[Artifact, ...]
    claims: tuple[Claim, ...]
    threads: tuple[Thread, ...]
    contradictions: tuple[Contradiction, ...]
    corroborations: tuple[Corroboration, ...]
    gaps: tuple[EvidenceGap, ...]
    timeline: tuple[Claim, ...]
    applicable_procedure_rules: tuple[dict, ...] = ()
    source_paths: dict[str, str] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dict with ISO timestamps."""

        def _dt(value: datetime | None) -> str | None:
            return value.isoformat() if value else None

        return {
            "case_id": self.case_id,
            "generated_at": _dt(self.generated_at),
            "disclaimer": (
                "DRAFT — REQUIRES LEGAL REVIEW — NOT LEGAL ADVICE. "
                "This dossier was generated by an evidence-organizing tool. "
                "It does not establish liability, prove wrongdoing, or render legal conclusions."
            ),
            "source_paths": self.source_paths,
            "actors": [
                {
                    "actor_id": a.actor_id,
                    "display_name": a.display_name,
                    "party_role": a.party_role,
                    "email_addresses": list(a.email_addresses),
                    "domains": list(a.domains),
                    "aliases": list(a.aliases),
                    "stake": a.stake,
                    "authority_level": a.authority_level,
                }
                for a in self.actors
            ],
            "artifacts": [
                {
                    "artifact_id": art.artifact_id,
                    "filename": art.filename,
                    "container_type": art.container_type,
                    "modality": art.modality,
                    "timestamp": _dt(art.timestamp),
                    "source_path": art.source_path,
                    "content_text": art.content_text[:2000] if art.content_text else "",
                    "metadata": art.metadata,
                    "anomalies": list(art.anomalies),
                    "extraction_errors": list(art.extraction_errors),
                }
                for art in self.artifacts
            ],
            "claims": [
                {
                    "claim_id": c.claim_id,
                    "text": c.text,
                    "source_artifact_ids": list(c.source_artifact_ids),
                    "actor_id": c.actor_id,
                    "timestamp": _dt(c.timestamp),
                    "modality": c.modality,
                    "claim_type": c.claim_type,
                    "confidence": c.confidence,
                    "extracted_by": c.extracted_by,
                    "supporting_evidence_ids": list(c.supporting_evidence_ids),
                }
                for c in self.claims
            ],
            "threads": [
                {
                    "thread_id": t.thread_id,
                    "subject": t.subject,
                    "participants": list(t.participants),
                    "initiator": t.initiator,
                    "messages": [
                        {
                            "artifact_id": m.artifact_id,
                            "actor_id": m.actor_id,
                            "timestamp": _dt(m.timestamp),
                            "subject": m.subject,
                            "body_excerpt": m.body_excerpt[:500],
                        }
                        for m in t.messages
                    ],
                }
                for t in self.threads
            ],
            "contradictions": [
                {
                    "claim_a_id": c.claim_a_id,
                    "claim_b_id": c.claim_b_id,
                    "reason": c.reason,
                    "normalized_subject": c.normalized_subject,
                    "confidence": c.confidence,
                }
                for c in self.contradictions
            ],
            "corroborations": [
                {
                    "claim_a_id": c.claim_a_id,
                    "claim_b_id": c.claim_b_id,
                    "reason": c.reason,
                    "normalized_subject": c.normalized_subject,
                    "confidence": c.confidence,
                }
                for c in self.corroborations
            ],
            "gaps": [
                {
                    "gap_id": g.gap_id,
                    "description": g.description,
                    "related_actor_ids": list(g.related_actor_ids),
                    "related_claim_ids": list(g.related_claim_ids),
                    "severity": g.severity,
                    "gap_type": g.gap_type,
                }
                for g in self.gaps
            ],
            "timeline": [
                {
                    "claim_id": c.claim_id,
                    "text": c.text,
                    "actor_id": c.actor_id,
                    "timestamp": _dt(c.timestamp),
                    "modality": c.modality,
                    "claim_type": c.claim_type,
                    "confidence": c.confidence,
                }
                for c in self.timeline
            ],
            "applicable_procedure_rules": list(self.applicable_procedure_rules),
        }
