"""Render a Dossier to Markdown and JSON strings."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from egregore.domain.self_rep_dossier.dossier_models import Dossier
from egregore.shared.canonical import canonical_dumps

DISCLAIMER = """DRAFT — REQUIRES LEGAL REVIEW — NOT LEGAL ADVICE

This dossier was generated by an evidence-organizing tool. It does not
establish liability, prove wrongdoing, or render legal conclusions. It must be
reviewed by a licensed attorney before use in any proceeding.
"""


def _fmt_ts(ts: datetime | None) -> str:
    return ts.strftime("%Y-%m-%d %H:%M") if ts else "(no date)"


def _actor_name(dossier: Dossier, actor_id: str) -> str:
    for actor in dossier.actors:
        if actor.actor_id == actor_id:
            return actor.display_name
    return actor_id


def _actor_role(dossier: Dossier, actor_id: str) -> str:
    for actor in dossier.actors:
        if actor.actor_id == actor_id:
            return actor.party_role
    return "unknown"


def render_markdown(dossier: Dossier) -> str:  # noqa: C901
    """Render the dossier as a Markdown document."""
    lines: list[str] = []

    lines.append(f"# Self-Representation Dossier: {dossier.case_id}")
    lines.append(f"\nGenerated: {_fmt_ts(dossier.generated_at)} UTC")
    lines.append(f"\n```\n{DISCLAIMER}\n```")

    # Sources
    lines.append("\n## Sources")
    for key, value in dossier.source_paths.items():
        lines.append(f"- **{key}**: `{value}`")

    # Actors
    lines.append("\n## Actors / Parties")
    for actor in sorted(dossier.actors, key=lambda a: a.party_role):
        lines.append(f"\n### {actor.display_name}")
        lines.append(f"- **Role**: {actor.party_role}")
        lines.append(f"- **Authority level**: {actor.authority_level}")
        lines.append(f"- **Stake**: {actor.stake}")
        if actor.email_addresses:
            lines.append(f"- **Emails**: {', '.join(actor.email_addresses)}")

    # Executive summary by party
    lines.append("\n## Party Narrative Summary")
    party_claims: dict[str, list[Any]] = {}
    for claim in dossier.claims:
        party_claims.setdefault(claim.actor_id, []).append(claim)

    for actor_id in sorted(party_claims.keys(), key=lambda a: _actor_role(dossier, a)):
        actor_name = _actor_name(dossier, actor_id)
        role = _actor_role(dossier, actor_id)
        claims = party_claims[actor_id]
        lines.append(f"\n### {actor_name} ({role})")
        lines.append(f"- Total claims extracted: {len(claims)}")
        for claim in sorted(claims, key=lambda c: c.timestamp or datetime.min)[:10]:
            lines.append(
                f"  - [{_fmt_ts(claim.timestamp)}] ({claim.modality}) {claim.text[:160]}"
            )
        if len(claims) > 10:
            lines.append(f"  - ... and {len(claims) - 10} more claims.")

    # Timeline
    lines.append("\n## Chronological Timeline")
    for claim in dossier.timeline[:100]:
        actor_name = _actor_name(dossier, claim.actor_id)
        lines.append(
            f"- {_fmt_ts(claim.timestamp)} | **{actor_name}** ({claim.modality}) | {claim.text[:180]}"
        )
    if len(dossier.timeline) > 100:
        lines.append(f"- ... and {len(dossier.timeline) - 100} more timeline events.")

    # Threads
    if dossier.threads:
        lines.append("\n## Email Threads")
        for thread in sorted(
            dossier.threads,
            key=lambda t: t.messages[0].timestamp if t.messages else datetime.min,
        ):
            lines.append(f"\n### {thread.subject}")
            lines.append(
                f"- Participants: {', '.join(_actor_name(dossier, p) for p in thread.participants)}"
            )
            lines.append(f"- Initiator: {_actor_name(dossier, thread.initiator)}")
            for msg in thread.messages[:15]:
                lines.append(
                    f"  - {_fmt_ts(msg.timestamp)} | {_actor_name(dossier, msg.actor_id)} | {msg.body_excerpt[:120]}"
                )
            if len(thread.messages) > 15:
                lines.append(f"  - ... and {len(thread.messages) - 15} more messages.")

    # Contradictions
    if dossier.contradictions:
        lines.append("\n## Contradictions")
        for c in dossier.contradictions[:50]:
            a_text = next(
                (cl.text for cl in dossier.claims if cl.claim_id == c.claim_a_id), ""
            )
            b_text = next(
                (cl.text for cl in dossier.claims if cl.claim_id == c.claim_b_id), ""
            )
            lines.append(f"\n- **{c.reason}** (confidence {c.confidence:.2f})")
            lines.append(f"  - A: {a_text[:160]}")
            lines.append(f"  - B: {b_text[:160]}")
        if len(dossier.contradictions) > 50:
            lines.append(
                f"\n... and {len(dossier.contradictions) - 50} more contradictions."
            )

    # Corroborations
    if dossier.corroborations:
        lines.append("\n## Corroborations")
        for c in dossier.corroborations[:30]:
            a_text = next(
                (cl.text for cl in dossier.claims if cl.claim_id == c.claim_a_id), ""
            )
            b_text = next(
                (cl.text for cl in dossier.claims if cl.claim_id == c.claim_b_id), ""
            )
            lines.append(f"\n- **{c.reason}** (confidence {c.confidence:.2f})")
            lines.append(f"  - A: {a_text[:160]}")
            lines.append(f"  - B: {b_text[:160]}")
        if len(dossier.corroborations) > 30:
            lines.append(
                f"\n... and {len(dossier.corroborations) - 30} more contradictions."
            )

    # Evidence gaps
    if dossier.gaps:
        lines.append("\n## Evidence Gaps")
        for gap in sorted(
            dossier.gaps, key=lambda g: (g.severity, g.gap_id), reverse=True
        ):
            actors = ", ".join(_actor_name(dossier, a) for a in gap.related_actor_ids)
            lines.append(f"\n- **[{gap.severity.upper()}] {gap.gap_type}** — {actors}")
            lines.append(f"  - {gap.description}")

    # Draft paragraphs
    lines.append("\n## Draft Fact Paragraphs (for legal review)")
    lines.append(
        "_These paragraphs are mechanically assembled from the timeline. They are NOT legal submissions._"
    )
    for i, claim in enumerate(dossier.timeline[:20], 1):
        actor_name = _actor_name(dossier, claim.actor_id)
        lines.append(
            f"\n{i}. On {_fmt_ts(claim.timestamp)}, {actor_name} produced a {claim.modality} "
            f'stating: "{claim.text[:200]}" (source: `{claim.source_artifact_ids[0]}`).'
        )

    # Quebec civil procedure & evidence appendix
    if dossier.applicable_procedure_rules:
        lines.append(
            "\n## Appendix — Applicable Quebec Civil Procedure & Evidence Rules"
        )
        lines.append(
            "_These rules are drawn from the provided procedure booklet. "
            "Verify current consolidation on LégisQuébec before filing._"
        )
        for rule in dossier.applicable_procedure_rules:
            lines.append(f"\n### {rule['rule_id']} — {rule['rule_text'][:120]}")
            lines.append(f"- **Confidence**: {rule['confidence']:.2f}")
            lines.append(f"- **Jurisdiction**: {rule['jurisdiction']}")
            if rule.get("triggering_claims"):
                lines.append("- **Triggered by claims**:")
                for tc in rule["triggering_claims"]:
                    lines.append(f"  - `{tc['claim_id']}`: {tc['text'][:140]}")

    lines.append(f"\n\n---\n{DISCLAIMER}")
    return "\n".join(lines)


def render_json(dossier: Dossier) -> str:
    """Render the dossier as a canonical JSON string."""
    return canonical_dumps(dossier.to_dict(), indent=2)
