"""
ANCHORUM Forensic Core
======================
Metadata intelligence platform foundation.
"""

from anchorum.forensic.core.canonicalization import (
    EntityExtractor,
    entity_id,
    merge_entities,
    normalize_email,
    normalize_organization,
    normalize_person,
)
from anchorum.forensic.core.extraction import (
    extract_email_metadata,
    extract_from_artifact,
    extract_image_metadata,
    extract_pdf_metadata,
    parse_pdf_date,
)
from anchorum.forensic.core.ingestion import (
    IngestionError,
    detect_container,
    hash_bytes,
    hash_file,
    ingest_artifact,
    ingest_directory,
)
from anchorum.forensic.core.types import (
    AnomalyFinding,
    AnomalyType,
    ApplicationMetadata,
    Artifact,
    CanonicalEntity,
    ContainerMetadata,
    ContainerType,
    ContentMetadata,
    EdgeType,
    EntityType,
    EventType,
    ExtractedMetadata,
    FsMetadata,
    GraphEdge,
    GraphNode,
    InvestigationReport,
    TemporalEvent,
    TemporalMetadata,
    TimelineEntry,
    to_canonical_json,
)

__all__ = [
    "Artifact",
    "ContainerType",
    "FsMetadata",
    "CanonicalEntity",
    "EntityType",
    "EdgeType",
    "AnomalyType",
    "EventType",
    "ExtractedMetadata",
    "ContainerMetadata",
    "ApplicationMetadata",
    "ContentMetadata",
    "TemporalMetadata",
    "TemporalEvent",
    "GraphNode",
    "GraphEdge",
    "TimelineEntry",
    "AnomalyFinding",
    "InvestigationReport",
    "to_canonical_json",
    "ingest_artifact",
    "ingest_directory",
    "detect_container",
    "hash_bytes",
    "hash_file",
    "IngestionError",
    "normalize_person",
    "normalize_organization",
    "normalize_email",
    "entity_id",
    "EntityExtractor",
    "merge_entities",
    "extract_email_metadata",
    "extract_from_artifact",
    "extract_image_metadata",
    "extract_pdf_metadata",
    "parse_pdf_date",
]
