[pioneer]
pioneer-1 ansible_host=192.168.2.11 ansible_user=aiops
pioneer-2 ansible_host=192.168.2.10 ansible_user=aiops
pioneer-3 ansible_host=192.168.2.133 ansible_user=aiops

[pioneer_nfs_server]
pioneer-2

[pioneer_orchestrator]
pioneer-1
